<?xml version="1.0" encoding="Windows-1250"?>
<!DOCTYPE schema [
<!ELEMENT schema (scale,left,top,width,height,id,name,comment,(entity*,atribute*,relation*,unique*,cardinality*,strong*)*)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT entity (left,top,width,height,id,name,comment)>
<!ELEMENT atribute (left,top,width,height,id,name,comment,datatype,arbitrary,(ent|rel))>
<!ELEMENT relation (left,top,width,height,id,name,comment)>
<!ELEMENT unique (left,top,width,height,id,name,comment,ent,atr*,primary)>
<!ELEMENT cardinality (left,top,width,height,id,name,comment,ent,rel,arbitrary,multi,glue)>
<!ELEMENT strong (left,top,width,height,ent,uni)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT arbitrary (#PCDATA)>
<!ELEMENT ent (#PCDATA)>
<!ELEMENT rel (#PCDATA)>
<!ELEMENT atr (#PCDATA)>
<!ELEMENT primary (#PCDATA)>
<!ELEMENT multi (#PCDATA)>
<!ELEMENT glue (#PCDATA)>
<!ELEMENT uni (#PCDATA)>
]>
<schema>
	<scale>1.1764706</scale>
	<left>0</left>
	<top>0</top>
	<width>2500</width>
	<height>2500</height>
	<id>34</id>
	<name>Schema</name>
	<comment></comment>
	<relation>
		<left>305</left>
		<top>299</top>
		<width>119</width>
		<height>39</height>
		<id>7</id>
		<name>Patri do</name>
		<comment></comment>
	</relation>
	<cardinality>
		<left>345</left>
		<top>236</top>
		<width>46</width>
		<height>29</height>
		<id>9</id>
		<name>Role2</name>
		<comment></comment>
		<ent>0</ent>
		<rel>7</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>314</left>
		<top>82</top>
		<width>107</width>
		<height>131</height>
		<id>0</id>
		<name>Projekt</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>463</left>
		<top>125</top>
		<width>41</width>
		<height>13</height>
		<id>3</id>
		<name>stav</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>0</ent>
	</atribute>
	<unique>
		<left>435</left>
		<top>92</top>
		<width>10</width>
		<height>10</height>
		<id>2</id>
		<name></name>
		<comment></comment>
		<ent>0</ent>
		<atr>1</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>461</left>
		<top>160</top>
		<width>93</width>
		<height>13</height>
		<id>4</id>
		<name>datum zadani</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<ent>0</ent>
	</atribute>
	<atribute>
		<left>461</left>
		<top>197</top>
		<width>98</width>
		<height>13</height>
		<id>5</id>
		<name>datum splneni</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>false</arbitrary>
		<ent>0</ent>
	</atribute>
	<atribute>
		<left>468</left>
		<top>92</top>
		<width>76</width>
		<height>13</height>
		<id>1</id>
		<name>id projektu</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>0</ent>
	</atribute>
	<cardinality>
		<left>515</left>
		<top>394</top>
		<width>46</width>
		<height>29</height>
		<id>17</id>
		<name>Role4</name>
		<comment></comment>
		<ent>14</ent>
		<rel>15</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<cardinality>
		<left>512</left>
		<top>350</top>
		<width>46</width>
		<height>29</height>
		<id>16</id>
		<name>Role3</name>
		<comment></comment>
		<ent>6</ent>
		<rel>15</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>572</left>
		<top>365</top>
		<width>119</width>
		<height>39</height>
		<id>15</id>
		<name>Patri do</name>
		<comment></comment>
	</relation>
	<cardinality>
		<left>713</left>
		<top>286</top>
		<width>34</width>
		<height>29</height>
		<id>22</id>
		<name></name>
		<comment></comment>
		<ent>6</ent>
		<rel>20</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<relation>
		<left>736</left>
		<top>247</top>
		<width>119</width>
		<height>39</height>
		<id>20</id>
		<name>Vlozil</name>
		<comment></comment>
	</relation>
	<relation>
		<left>743</left>
		<top>352</top>
		<width>119</width>
		<height>39</height>
		<id>23</id>
		<name>Je smerovan</name>
		<comment></comment>
	</relation>
	<cardinality>
		<left>865</left>
		<top>393</top>
		<width>34</width>
		<height>29</height>
		<id>24</id>
		<name></name>
		<comment></comment>
		<ent>19</ent>
		<rel>23</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<cardinality>
		<left>868</left>
		<top>238</top>
		<width>34</width>
		<height>29</height>
		<id>21</id>
		<name></name>
		<comment></comment>
		<ent>19</ent>
		<rel>20</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>574</left>
		<top>420</top>
		<width>113</width>
		<height>68</height>
		<id>14</id>
		<name>Soubor</name>
		<comment></comment>
	</entity>
	<unique>
		<left>581</left>
		<top>515</top>
		<width>10</width>
		<height>10</height>
		<id>30</id>
		<name></name>
		<comment></comment>
		<ent>14</ent>
		<atr>29</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>600</left>
		<top>522</top>
		<width>50</width>
		<height>13</height>
		<id>26</id>
		<name>nazev</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<ent>14</ent>
	</atribute>
	<atribute>
		<left>619</left>
		<top>502</top>
		<width>49</width>
		<height>13</height>
		<id>27</id>
		<name>cesta</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<ent>14</ent>
	</atribute>
	<atribute>
		<left>581</left>
		<top>542</top>
		<width>29</width>
		<height>13</height>
		<id>29</id>
		<name>id</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>14</ent>
	</atribute>
	<cardinality>
		<left>466</left>
		<top>303</top>
		<width>46</width>
		<height>29</height>
		<id>8</id>
		<name>Role1</name>
		<comment></comment>
		<ent>6</ent>
		<rel>7</rel>
		<arbitrary>true</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
	<entity>
		<left>867</left>
		<top>302</top>
		<width>106</width>
		<height>51</height>
		<id>19</id>
		<name>Uzivatel</name>
		<comment></comment>
	</entity>
	<atribute>
		<left>1000</left>
		<top>294</top>
		<width>67</width>
		<height>13</height>
		<id>33</id>
		<name>Atribute3</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>19</ent>
	</atribute>
	<atribute>
		<left>999</left>
		<top>322</top>
		<width>67</width>
		<height>13</height>
		<id>31</id>
		<name>Atribute1</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>19</ent>
	</atribute>
	<atribute>
		<left>996</left>
		<top>349</top>
		<width>67</width>
		<height>13</height>
		<id>32</id>
		<name>Atribute2</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>false</arbitrary>
		<ent>19</ent>
	</atribute>
	<cardinality>
		<left>713</left>
		<top>321</top>
		<width>34</width>
		<height>29</height>
		<id>25</id>
		<name></name>
		<comment></comment>
		<ent>6</ent>
		<rel>23</rel>
		<arbitrary>false</arbitrary>
		<multi>false</multi>
		<glue>false</glue>
	</cardinality>
	<entity>
		<left>569</left>
		<top>293</top>
		<width>113</width>
		<height>50</height>
		<id>6</id>
		<name>Prispevek</name>
		<comment></comment>
	</entity>
	<unique>
		<left>563</left>
		<top>270</top>
		<width>10</width>
		<height>10</height>
		<id>11</id>
		<name></name>
		<comment></comment>
		<ent>6</ent>
		<atr>10</atr>
		<primary>true</primary>
	</unique>
	<atribute>
		<left>562</left>
		<top>241</top>
		<width>85</width>
		<height>13</height>
		<id>10</id>
		<name>id prispevku</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<ent>6</ent>
	</atribute>
	<atribute>
		<left>578</left>
		<top>262</top>
		<width>37</width>
		<height>13</height>
		<id>12</id>
		<name>text</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<ent>6</ent>
	</atribute>
	<atribute>
		<left>623</left>
		<top>262</top>
		<width>94</width>
		<height>13</height>
		<id>13</id>
		<name>datum vlozeni</name>
		<comment></comment>
		<datatype>Date</datatype>
		<arbitrary>true</arbitrary>
		<ent>6</ent>
	</atribute>
</schema>
